### ISSUE TITLE
Missing Includes?

### ISSUE THREAD

**Issue by alxspiker** [IndividualCoder/UrsinaEditor#1]
![image](https://github.com/IndividualCoder/UrsinaEditor/assets/7357054/ba352730-ad13-4cb3-9b1f-cd5db5b70b23)

**Comment by alxspiker** [comment]
Another one
![image](https://github.com/IndividualCoder/UrsinaEditor/assets/7357054/88cf117d-49c0-4235-9bcf-8519df5ce935)

**Comment by IndividualCoder** [comment]
what I think is
you have just opened the main.py file. not the folder open the editor folder and this will work

**Comment by alxspiker** [comment]
You are right! Now just one more issue, the dropdown file seems missing.
![image](https://github.com/IndividualCoder/UrsinaEditor/assets/7357054/3bdaf058-5f4f-41a3-99c7-4ae6647acb4f)

**Comment by alxspiker** [comment]
Nevermind, did a new pull and its launching.

**Comment by IndividualCoder** [comment]
you need to download the lates version of ursina editor and replace your ursina folder with my ursina repo

**Comment by alxspiker** [comment]
Doesn't seem like it, I am using the pip install version and it seems to be working fine.

**Comment by IndividualCoder** [comment]
it will work but not as I intended
and will produce an error in some cases
